services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle
    env_file:
      - .envdir/development/database
      - .envdir/development/web
    depends_on:
      - database
    tty: true
    stdin_open: true

  database:
    image: postgres:18
    env_file:
      - .envdir/development/database
    volumes:
      - postgres:/var/lib/postgresql
    # ports:
      # - 5432:5432

volumes:
  gem_cache:
  postgres:
